name: Terraform checks
on: [push, pull_request]

jobs:
  terraform-linter:
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive

      - name: Terraform Init
        id: init-zpa-app-connector-group
        run: |
          cd modules/terraform-zpa-app-connector-group
          terraform init   

      - name: Terraform Validate
        id: validate-zpa-app-connector-group
        run: |
          cd modules/terraform-zpa-app-connector-group
          terraform validate -no-color

      - name: Terraform Init
        id: init-zpa-provisioning-key
        run: |
          cd modules/terraform-zpa-provisioning-key
          terraform init   

      - name: Terraform Validate
        id: validate-zpa-provisioning-key
        run: |
          cd modules/terraform-zpa-provisioning-key
          terraform validate -no-color

      - name: Terraform Init
        id: init-zsbc-bcvm-libvirt
        run: |
          cd modules/terraform-zsbc-bcvm-libvirt
          terraform init   

      - name: Terraform Validate
        id: validate-zsbc-bcvm-libvirt
        run: |
          cd modules/terraform-zsbc-bcvm-libvirt
          terraform validate -no-color
